### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by GuJiaWen777** [jiaor17/DiffCSP-PP#3]
https://github.com/jiaor17/DiffCSP-PP/blob/d5c176b5f61a54ea2facc11532329b545b401d94/diffcsp/pl_modules/diffusion_w_type.py#L296
Hello，Is the code supposed to be written like this?
`res = dict(traj[0])`

**Comment by jiaor17** [comment]
Hi,
Thanks for pointing it out. Here `dc` means `copy.deepcopy`, and the missing requirement is now updated as
```
from copy import deepcopy as dc
```

**Comment by GuJiaWen777** [comment]
Thanks for replying!
