### ISSUE TITLE
How to use trained weights for structure prediction?

### ISSUE THREAD

**Issue by chachapro** [jiaor17/DiffCSP-PP#5]
Thank you for open sourcing your code！
However, I notice that DiffCSP-PP does not provide prediction code. Can I use DiffCSP-PP trained weight files for prediction using DiffCSP code?
Or will you open source the prediction code for DiffCSP-PP in the future？

**Comment by jiaor17** [comment]
Hi,
Thanks for your interest! The evaluation scripts are provided in the [eval](https://github.com/jiaor17/DiffCSP-PP/tree/eval) branch. Feel free to check them!

**Comment by chachapro** [comment]
Thank you for your reply！
