### ISSUE TITLE
Tool/package for crystal structure visualization

### ISSUE THREAD

**Issue by nayoung10** [jiaor17/DiffCSP-PP#6]
Hi,

Which tool/package have you used to create the following visualization in your paper?
Thank you in advance for your help!

![image](https://github.com/user-attachments/assets/5a36693b-ade9-4a7f-ac90-56831545817a)

**Comment by jiaor17** [comment]
Hi,
We use [ase](https://wiki.fysik.dtu.dk/ase/ase/visualize/visualize.html) to visualize the generated results.

**Comment by lkny123** [comment]
Thanks for the reply!

**Comment by nayoung10** [comment]
Thanks for the reply!
